package com.example.trivialapp_base.model

// Definición de la clase de datos Pregunta según requisitos
data class Pregunta(
    val pregunta: String,
    val categoria: String,
    val dificultad: String, // "Facil", "Medio", "Dificil"
    val respuesta1: String,
    val respuesta2: String,
    val respuesta3: String,
    val respuesta4: String,
    val respuestaCorrecta: String // Debe coincidir con una de las anteriores
)

// Objeto para simular la base de datos local (Hardcoded)
object ProveedorPreguntas {
    fun obtenerPreguntas(): MutableList<Pregunta> {
        return mutableListOf(
            // --- NIVEL FÁCIL (30 Preguntas) ---
            Pregunta("¿Capital de Francia?", "Geografía", "Facil", "Madrid", "París", "Berlin", "Roma", "París"),
            Pregunta("¿Fórmula del agua?", "Ciencia", "Facil", "H2O", "CO2", "O2", "H2O2", "H2O"),
            Pregunta("¿Color del caballo blanco de Santiago?", "Lógica", "Facil", "Negro", "Marrón", "Blanco", "Gris", "Blanco"),
            Pregunta("¿Cuántos días tiene una semana?", "General", "Facil", "5", "6", "7", "8", "7"),
            Pregunta("¿Animal que ladra?", "Biología", "Facil", "Gato", "Perro", "Vaca", "Pájaro", "Perro"),
            Pregunta("¿Capital de España?", "Geografía", "Facil", "Barcelona", "Sevilla", "Madrid", "Valencia", "Madrid"),
            Pregunta("¿Resultado de 2 + 2?", "Matemáticas", "Facil", "3", "4", "5", "22", "4"),
            Pregunta("¿Planeta donde vivimos?", "Ciencia", "Facil", "Marte", "Venus", "Tierra", "Luna", "Tierra"),
            Pregunta("¿Idioma oficial de México?", "Cultura", "Facil", "Inglés", "Portugués", "Español", "Francés", "Español"),
            Pregunta("¿Cuántas patas tiene una araña?", "Biología", "Facil", "6", "8", "4", "10", "8"),
            Pregunta("¿Rey de la selva?", "Biología", "Facil", "Tigre", "Elefante", "León", "Mono", "León"),
            Pregunta("¿Estación más calurosa?", "General", "Facil", "Invierno", "Otoño", "Primavera", "Verano", "Verano"),
            Pregunta("¿Instrumento con teclas blancas y negras?", "Música", "Facil", "Guitarra", "Violín", "Piano", "Flauta", "Piano"),
            Pregunta("¿Opuesto de 'Blanco'?", "General", "Facil", "Rojo", "Azul", "Negro", "Verde", "Negro"),
            Pregunta("¿Moneda de Estados Unidos?", "Economía", "Facil", "Euro", "Dólar", "Peso", "Libra", "Dólar"),
            Pregunta("¿Fruta prohibida de Adán y Eva?", "Religión", "Facil", "Pera", "Plátano", "Manzana", "Uva", "Manzana"),
            Pregunta("¿Continente de Egipto?", "Geografía", "Facil", "Europa", "Asia", "África", "América", "África"),
            Pregunta("¿Deporte de Messi?", "Deportes", "Facil", "Tenis", "Fútbol", "Baloncesto", "Golf", "Fútbol"),
            Pregunta("¿Líquido vital para la vida?", "Ciencia", "Facil", "Aceite", "Agua", "Leche", "Zumo", "Agua"),
            Pregunta("¿Cuántos minutos tiene una hora?", "General", "Facil", "30", "60", "90", "100", "60"),
            Pregunta("¿Símbolo químico del Oxígeno?", "Química", "Facil", "Ox", "O", "Oi", "On", "O"),
            Pregunta("¿Personaje principal de Mario Bros?", "Videojuegos", "Facil", "Luigi", "Peach", "Mario", "Bowser", "Mario"),
            Pregunta("¿Satélite natural de la Tierra?", "Astronomía", "Facil", "Sol", "Marte", "Luna", "Estrella", "Luna"),
            Pregunta("¿Mejor amigo del hombre?", "Biología", "Facil", "Gato", "Caballo", "Perro", "Loro", "Perro"),
            Pregunta("¿Color del cielo despejado?", "General", "Facil", "Verde", "Rojo", "Azul", "Amarillo", "Azul"),
            Pregunta("¿Mes con menos días?", "General", "Facil", "Enero", "Febrero", "Marzo", "Abril", "Febrero"),
            Pregunta("¿Número de lados de un triángulo?", "Geometría", "Facil", "3", "4", "5", "6", "3"),
            Pregunta("¿Sentido para escuchar?", "Biología", "Facil", "Vista", "Olfato", "Gusto", "Oído", "Oído"),
            Pregunta("¿País de la Torre Eiffel?", "Geografía", "Facil", "Italia", "Francia", "Alemania", "Inglaterra", "Francia"),
            Pregunta("¿Vehículo de dos ruedas?", "Transporte", "Facil", "Coche", "Camión", "Bicicleta", "Barco", "Bicicleta"),

            // --- NIVEL MEDIO (30 Preguntas) ---
            Pregunta("¿Quién pintó la Mona Lisa?", "Arte", "Medio", "Picasso", "Van Gogh", "Da Vinci", "Dalí", "Da Vinci"),
            Pregunta("¿Planeta más grande del sistema solar?", "Ciencia", "Medio", "Tierra", "Marte", "Júpiter", "Saturno", "Júpiter"),
            Pregunta("¿Año descubrimiento América?", "Historia", "Medio", "1492", "1500", "1485", "1992", "1492"),
            Pregunta("¿Capital de Alemania?", "Geografía", "Medio", "Múnich", "Berlín", "Hamburgo", "Frankfurt", "Berlín"),
            Pregunta("¿Hueso más largo del cuerpo?", "Anatomía", "Medio", "Fémur", "Tibia", "Húmero", "Radio", "Fémur"),
            Pregunta("¿Moneda de Japón?", "Economía", "Medio", "Yuan", "Won", "Yen", "Dólar", "Yen"),
            Pregunta("¿Autor de Harry Potter?", "Literatura", "Medio", "Tolkien", "J.K. Rowling", "G.R.R. Martin", "Stephen King", "J.K. Rowling"),
            Pregunta("¿Elemento químico Fe?", "Química", "Medio", "Fósforo", "Flúor", "Hierro", "Francio", "Hierro"),
            Pregunta("¿Cuántos continentes hay (modelo 5)?", "Geografía", "Medio", "4", "5", "6", "7", "5"),
            Pregunta("¿Diosa griega de la sabiduría?", "Mitología", "Medio", "Venus", "Atenea", "Hera", "Afrodita", "Atenea"),
            Pregunta("¿País con forma de bota?", "Geografía", "Medio", "España", "Grecia", "Italia", "Portugal", "Italia"),
            Pregunta("¿Ganador Mundial Fútbol 2014?", "Deportes", "Medio", "Argentina", "Brasil", "Alemania", "España", "Alemania"),
            Pregunta("¿Cuántas teclas tiene un piano estándar?", "Música", "Medio", "66", "77", "88", "99", "88"),
            Pregunta("¿Cervantes o Shakespeare murió antes?", "Literatura", "Medio", "Cervantes", "Shakespeare", "Mismo día (aprox)", "Ninguno", "Mismo día (aprox)"),
            Pregunta("¿Río más largo del mundo?", "Geografía", "Medio", "Nilo", "Amazonas", "Misisipi", "Yangtsé", "Amazonas"),
            Pregunta("¿Gas más abundante en la atmósfera?", "Ciencia", "Medio", "Oxígeno", "Nitrógeno", "Hidrógeno", "Helio", "Nitrógeno"),
            Pregunta("¿Fundador de Microsoft?", "Tecnología", "Medio", "Steve Jobs", "Bill Gates", "Elon Musk", "Mark Zuckerberg", "Bill Gates"),
            Pregunta("¿Capital de Australia?", "Geografía", "Medio", "Sídney", "Melbourne", "Canberra", "Perth", "Canberra"),
            Pregunta("¿Primer hombre en la Luna?", "Historia", "Medio", "Yuri Gagarin", "Buzz Aldrin", "Neil Armstrong", "Michael Collins", "Neil Armstrong"),
            Pregunta("¿Animal terrestre más rápido?", "Biología", "Medio", "León", "Gacela", "Guepardo", "Caballo", "Guepardo"),
            Pregunta("¿Libro sagrado del Islam?", "Religión", "Medio", "Biblia", "Torá", "Corán", "Vedas", "Corán"),
            Pregunta("¿Qué estudia la micología?", "Ciencia", "Medio", "Minerales", "Hongos", "Músculos", "Estrellas", "Hongos"),
            Pregunta("¿Pintor de 'La noche estrellada'?", "Arte", "Medio", "Monet", "Manet", "Van Gogh", "Picasso", "Van Gogh"),
            Pregunta("¿Cuántos corazones tiene un pulpo?", "Biología", "Medio", "1", "2", "3", "4", "3"),
            Pregunta("¿Siglo de la Revolución Francesa?", "Historia", "Medio", "XVII", "XVIII", "XIX", "XX", "XVIII"),
            Pregunta("¿País más grande del mundo?", "Geografía", "Medio", "China", "EEUU", "Canadá", "Rusia", "Rusia"),
            Pregunta("¿Director de 'Jurassic Park'?", "Cine", "Medio", "Lucas", "Spielberg", "Cameron", "Nolan", "Spielberg"),
            Pregunta("¿Metal líquido a temperatura ambiente?", "Química", "Medio", "Plomo", "Mercurio", "Estaño", "Zinc", "Mercurio"),
            Pregunta("¿Cuántos jugadores hay en un equipo de voleibol?", "Deportes", "Medio", "5", "6", "7", "11", "6"),
            Pregunta("¿Capital de Canadá?", "Geografía", "Medio", "Toronto", "Vancouver", "Ottawa", "Montreal", "Ottawa"),

            // --- NIVEL DIFÍCIL (30 Preguntas) ---
            Pregunta("¿Elemento químico Au?", "Química", "Dificil", "Plata", "Oro", "Cobre", "Aluminio", "Oro"),
            Pregunta("¿Velocidad de la luz?", "Física", "Dificil", "300.000 km/s", "150.000 km/s", "1000 km/s", "Mach 1", "300.000 km/s"),
            Pregunta("¿Año caída Muro de Berlín?", "Historia", "Dificil", "1987", "1989", "1991", "1993", "1989"),
            Pregunta("¿Capital de Kazajistán?", "Geografía", "Dificil", "Almaty", "Astaná", "Taskent", "Biskek", "Astaná"),
            Pregunta("¿Autor de 'Cien años de soledad'?", "Literatura", "Dificil", "Vargas Llosa", "Cortázar", "García Márquez", "Borges", "García Márquez"),
            Pregunta("¿Montaña más alta de África?", "Geografía", "Dificil", "Everest", "K2", "Kilimanjaro", "Aconcagua", "Kilimanjaro"),
            Pregunta("¿Guerra de los Cien Años duró...?", "Historia", "Dificil", "100 años", "116 años", "99 años", "101 años", "116 años"),
            Pregunta("¿Quién descubrió la penicilina?", "Ciencia", "Dificil", "Pasteur", "Fleming", "Curie", "Darwin", "Fleming"),
            Pregunta("¿Dios egipcio de la muerte?", "Mitología", "Dificil", "Ra", "Horus", "Anubis", "Osiris", "Anubis"),
            Pregunta("¿Número atómico del Carbono?", "Química", "Dificil", "6", "12", "14", "8", "6"),
            Pregunta("¿Capital de Turquía?", "Geografía", "Dificil", "Estambul", "Ankara", "Esmirna", "Antalya", "Ankara"),
            Pregunta("¿Primer presidente de EEUU?", "Historia", "Dificil", "Lincoln", "Jefferson", "Washington", "Franklin", "Washington"),
            Pregunta("¿Filósofo del mito de la caverna?", "Filosofía", "Dificil", "Sócrates", "Aristóteles", "Platón", "Descartes", "Platón"),
            Pregunta("¿Año inicio Primera Guerra Mundial?", "Historia", "Dificil", "1912", "1914", "1918", "1939", "1914"),
            Pregunta("¿Moneda de Suiza?", "Economía", "Dificil", "Euro", "Dólar", "Franco suizo", "Corona", "Franco suizo"),
            Pregunta("¿Isla más grande del Mediterráneo?", "Geografía", "Dificil", "Cerdeña", "Córcega", "Sicilia", "Creta", "Sicilia"),
            Pregunta("¿Autor de 'La Divina Comedia'?", "Literatura", "Dificil", "Dante", "Petrarca", "Boccaccio", "Maquiavelo", "Dante"),
            Pregunta("¿País con más islas del mundo?", "Geografía", "Dificil", "Filipinas", "Indonesia", "Suecia", "Canadá", "Suecia"),
            Pregunta("¿Quién formuló la Teoría de la Relatividad?", "Física", "Dificil", "Newton", "Einstein", "Hawking", "Bohr", "Einstein"),
            Pregunta("¿Cuántos huesos tiene el cuerpo humano adulto?", "Anatomía", "Dificil", "200", "206", "210", "212", "206"),
            Pregunta("¿Año llegada hombre a la Luna?", "Historia", "Dificil", "1965", "1969", "1971", "1959", "1969"),
            Pregunta("¿Capital de Nueva Zelanda?", "Geografía", "Dificil", "Auckland", "Wellington", "Christchurch", "Sídney", "Wellington"),
            Pregunta("¿Nombre real de Buda?", "Religión", "Dificil", "Siddhartha Gautama", "Ghandi", "Dalai Lama", "Krishna", "Siddhartha Gautama"),
            Pregunta("¿Metal más caro del mundo (aprox)?", "Economía", "Dificil", "Oro", "Platino", "Rodio", "Paladio", "Rodio"),
            Pregunta("¿Estrecho entre España y África?", "Geografía", "Dificil", "Bósforo", "Gibraltar", "Ormuz", "Magallanes", "Gibraltar"),
            Pregunta("¿Pintor de 'Las Meninas'?", "Arte", "Dificil", "Goya", "El Greco", "Velázquez", "Murillo", "Velázquez"),
            Pregunta("¿Cuántas casillas tiene un tablero de ajedrez?", "Juegos", "Dificil", "60", "64", "68", "72", "64"),
            Pregunta("¿País origen del café?", "Historia", "Dificil", "Colombia", "Brasil", "Etiopía", "Vietnam", "Etiopía"),
            Pregunta("¿Satélite más grande de Saturno?", "Astronomía", "Dificil", "Europa", "Titán", "Ío", "Ganimedes", "Titán"),
            Pregunta("¿Quién escribió 'El origen de las especies'?", "Ciencia", "Dificil", "Lamarck", "Darwin", "Mendel", "Wallace", "Darwin")
        )
    }
}